apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple
  labels:
    app: apple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      labels:
        app: apple
    spec:
      containers:
        - name: apple
          # タグはCIが書き換える(.github/workflows/ci.yml)
          image: ghcr.io/heyshi/develop-pe-env-apple:init
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests: { cpu: 25m, memory: 64Mi }
