apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-alpha-apple
  namespace: ns-gitops-team-alpha-sys-apple
spec:
  project: appproj-alpha-workloads
  source:
    repoURL: https://github.com/heyshi-organization/idp-gitops-application.git
    targetRevision: main
    path: manifests/apple
  destination:
    server: https://kubernetes.default.svc
    namespace: ns-gitops-team-alpha-sys-apple
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
